ajout du nombre d'évènement au dessus de la ligne du temps
Drahakar/vireauvert pull request #52
Opened 2022-08-20 01:44 UTC by Drahakar

Pas mal de base, mais c'est pour donner un aperçu.

Aussi, je voulais discuter avec vous pour le truc de l'enum dont vous discutiez plus tot

![image](https://user-images.githubusercontent.com/495858/185724557-e98ccf0a-05ac-4df3-b342-90baa0e06f54.png)

2022-08-20 01:48 UTC, Drahakar commented
je pense qu'on est limité à seulement afficher le nombre d'événement au dessus des points ayant un label, ça semble une limitation du vue-slider ...

2022-08-20 01:49 UTC, Drahakar commented on src/components/Timeline.vue
> +    transform: translate(0%, -200%);
ça ne centre pas réellement les nombre sur l'axe avec les labels, je vais gosser pour trouver une meilleure solution plus tard.

2022-08-20 02:40 UTC, edemartel requested changes

2022-08-20 02:40 UTC, edemartel commented on src/components/Timeline.vue
> +                    <!--<div :class="['vue-slider-mark-label', 'custom-label', 'event-count']">{{catastrophesCountByYears(value)}}</div>-->
Idéalement j'éviterais de laisser du code commenté. Si c'est pertinent on peut retourner le chercher dans l'historique.

2022-08-21 00:56 UTC, Drahakar commented on src/components/Timeline.vue
> +                    <!--<div :class="['vue-slider-mark-label', 'custom-label', 'event-count']">{{catastrophesCountByYears(value)}}</div>-->
c'était pas voulu ^_^

2022-08-21 15:23 UTC, Drahakar commented on src/components/Timeline.vue
> +                'width:' + (100-(TIMELINE_YEARS.filter(x => x <= BEGIN_MODELED_YEAR).length/TIMELINE_YEARS.length * 100)) + '%'
ça serait quoi la meilleure façon de ne pas répéter ce calcul la?

2022-08-21 15:23 UTC, Drahakar commented on src/components/Timeline.vue
> +                'width:' + (100-(TIMELINE_YEARS.filter(x => x <= BEGIN_MODELED_YEAR).length/TIMELINE_YEARS.length * 100)) + '%'
Je slap une fonction bête a quelque part ou est-ce qu'il existe un truc idiomatique vue?

2022-08-21 16:30 UTC, edemartel commented on src/components/Timeline.vue
> +                'width:' + (100-(TIMELINE_YEARS.filter(x => x <= BEGIN_MODELED_YEAR).length/TIMELINE_YEARS.length * 100)) + '%'
Une computed property.

2022-08-21 16:33 UTC, edemartel commented on src/components/Timeline.vue
> +                'width:' + (100-(TIMELINE_YEARS.filter(x => x <= BEGIN_MODELED_YEAR).length/TIMELINE_YEARS.length * 100)) + '%'
Fait une fonction avec.

2022-08-21 16:52 UTC, edemartel commented on src/components/Timeline.vue
> +                'width:' + (100-(TIMELINE_YEARS.filter(x => x <= BEGIN_MODELED_YEAR).length/TIMELINE_YEARS.length * 100)) + '%'
Mais t'as pas à faire de fonction, juste une variable locale:

    const ratio = TIMELINE_YEARS.filter(x => x <= BEGIN_MODELED_YEAR).length / TIMELINE_YEARS.length;
    return {
        marks: TIMELINE_YEARS.filter(x => x % 5 === 0),
        years: TIMELINE_YEARS,
        modeledYearsStyle: [
            'left:' + (ratio * 100) + '%', 
            'width:' + ((1 - ratio) * 100) + '%'
        ]   
    }

2022-08-21 17:08 UTC, Drahakar commented on src/components/Timeline.vue
> +                'width:' + (100-(TIMELINE_YEARS.filter(x => x <= BEGIN_MODELED_YEAR).length/TIMELINE_YEARS.length * 100)) + '%'
Ah bin oui 😅

2022-08-21 18:34 UTC, edemartel commented
Faudrait cacher les décomptes d'événements sur les années > 2022.

2022-08-22 01:52 UTC, Drahakar commented
> Faudrait cacher les décomptes d'événements sur les années > 2022.

Ouais c'est aussi une réflexion que j'ai eu, je vais faire ça dans une autre PR

2022-08-22 01:58 UTC, edemartel commented on src/components/Timeline.vue
> +                'width:' + (100-(TIMELINE_YEARS.filter(x => x <= BEGIN_MODELED_YEAR).length/TIMELINE_YEARS.length * 100)) + '%'
Mais ouais faudrait que tu changes ça.

2022-08-22 02:02 UTC, edemartel approved these changes

2022-08-22 02:07 UTC, merged