collapse la liste des candidats par défaut sur desktop
Drahakar/vireauvert pull request #80
Opened 2022-08-25 02:48 UTC by Drahakar

2022-08-25 02:51 UTC, Drahakar commented on src/components/CandidateList.vue
> +        <ul id="body-candidates" :class="['list-group', 'list-group-flush', 'collapse', {'show': isMobile}]" ref="candidates">
hum je pense que collapse serait un meilleur nom. brb.

2022-08-26 01:23 UTC, edemartel requested changes

2022-08-26 01:23 UTC, edemartel commented on src/components/CandidateList.vue
> +        <ul id="body-candidates" :class="['list-group', 'list-group-flush', 'collapse', {'show': collapse}]" ref="candidates">
Tu peux utiliser à la fois `class` et `:class` et Vue va combiner les deux.

2022-08-26 01:23 UTC, edemartel commented on src/components/CandidateList.vue
> +            <a data-bs-toggle="collapse" href="#body-candidates" :aria-expanded="{collapse}" aria-controls="body-candidates"
`collapse`, pas `{collapse}`.

2022-08-26 01:23 UTC, edemartel commented on src/components/CandidateList.vue
> +                id="heading-candidates" :class="['d-block', {'collapsed': !collapse}]">
Voir ci-haut.

2022-08-26 02:09 UTC, Drahakar commented on src/components/CandidateList.vue
> +            <a data-bs-toggle="collapse" href="#body-candidates" :aria-expanded="{collapse}" aria-controls="body-candidates"
non ça ne marche pas ça non plus.

2022-08-26 02:31 UTC, edemartel approved these changes

2022-08-26 14:57 UTC, merged